-- FitPlanCoach starter catalog: real foods + real workout programming.
-- Safe to re-run: each block clears its own table first (catalog data only,
-- never touches users/profiles/subscriptions/etc).

delete from public.foods;
delete from public.workout_templates;
delete from public.exercises;

insert into public.foods (name, country, calories_per_100g, protein_per_100g, category, budget_level) values
  ('Oats', 'global', 389, 16.9, 'breakfast', 'low'),
  ('Eggs', 'global', 155, 13.0, 'breakfast', 'low'),
  ('Banana', 'global', 89, 1.1, 'breakfast', 'low'),
  ('Greek Yogurt (nonfat)', 'global', 59, 10.3, 'breakfast', 'medium'),
  ('Whole Wheat Bread', 'global', 247, 13.0, 'breakfast', 'medium'),
  ('Peanut Butter', 'global', 588, 25.0, 'breakfast', 'medium'),
  ('Smoked Salmon', 'global', 117, 18.3, 'breakfast', 'high'),
  ('Avocado', 'global', 160, 2.0, 'breakfast', 'high'),
  ('Cottage Cheese', 'global', 98, 11.0, 'breakfast', 'high'),
  ('White Rice (cooked)', 'global', 130, 2.7, 'lunch', 'low'),
  ('Lentils (cooked)', 'global', 116, 9.0, 'lunch', 'low'),
  ('Canned Tuna', 'global', 132, 28.0, 'lunch', 'low'),
  ('Chicken Breast', 'global', 165, 31.0, 'lunch', 'medium'),
  ('Pasta (cooked)', 'global', 131, 5.0, 'lunch', 'medium'),
  ('Sweet Potato', 'global', 86, 1.6, 'lunch', 'medium'),
  ('Salmon Fillet', 'global', 208, 20.0, 'lunch', 'high'),
  ('Beef Sirloin', 'global', 271, 26.0, 'lunch', 'high'),
  ('Quinoa (cooked)', 'global', 120, 4.4, 'lunch', 'high'),
  ('Black Beans (cooked)', 'global', 127, 8.7, 'dinner', 'low'),
  ('Potatoes (boiled)', 'global', 77, 2.0, 'dinner', 'low'),
  ('Canned Tuna', 'global', 132, 28.0, 'dinner', 'low'),
  ('Ground Beef 90/10', 'global', 176, 20.0, 'dinner', 'medium'),
  ('Chicken Breast', 'global', 165, 31.0, 'dinner', 'medium'),
  ('Brown Rice (cooked)', 'global', 123, 2.7, 'dinner', 'medium'),
  ('Shrimp', 'global', 99, 24.0, 'dinner', 'high'),
  ('Salmon Fillet', 'global', 208, 20.0, 'dinner', 'high'),
  ('Steak (sirloin)', 'global', 271, 26.0, 'dinner', 'high'),
  ('Apple', 'global', 52, 0.3, 'snack', 'low'),
  ('Peanuts', 'global', 567, 25.8, 'snack', 'low'),
  ('Rice Cakes', 'global', 387, 8.0, 'snack', 'low'),
  ('Almonds', 'global', 579, 21.0, 'snack', 'medium'),
  ('Part-Skim Mozzarella', 'global', 280, 28.0, 'snack', 'medium'),
  ('Protein Bar', 'global', 350, 20.0, 'snack', 'medium'),
  ('Mixed Nuts', 'global', 600, 20.0, 'snack', 'high'),
  ('Beef Jerky', 'global', 410, 33.0, 'snack', 'high'),
  ('Whey Protein Powder', 'global', 400, 80.0, 'snack', 'high');

insert into public.workout_templates (name, goal, level, schedule) values
  ('Fat Loss — Full Body Starter', 'lose_fat', 'beginner', '[{"day": "Mon", "focus": "Full Body A", "items": [{"name": "Bodyweight Squat", "sets": 3, "reps": "15-20", "rest_seconds": 45}, {"name": "Push-Up (knee or full)", "sets": 3, "reps": "10-15", "rest_seconds": 45}, {"name": "Dumbbell Row", "sets": 3, "reps": "12-15", "rest_seconds": 45}, {"name": "Glute Bridge", "sets": 3, "reps": "15-20", "rest_seconds": 45}, {"name": "Plank", "sets": 3, "reps": "30-45s", "rest_seconds": 30}]}, {"day": "Wed", "focus": "Full Body B", "items": [{"name": "Walking Lunge", "sets": 3, "reps": "12/leg", "rest_seconds": 45}, {"name": "Incline Push-Up", "sets": 3, "reps": "12-15", "rest_seconds": 45}, {"name": "Lat Pulldown", "sets": 3, "reps": "12-15", "rest_seconds": 45}, {"name": "Step-Up", "sets": 3, "reps": "12/leg", "rest_seconds": 45}, {"name": "Mountain Climbers", "sets": 3, "reps": "30s", "rest_seconds": 30}]}, {"day": "Fri", "focus": "Full Body C + Cardio", "items": [{"name": "Goblet Squat", "sets": 3, "reps": "15", "rest_seconds": 45}, {"name": "Seated Row", "sets": 3, "reps": "12-15", "rest_seconds": 45}, {"name": "Dumbbell Shoulder Press", "sets": 3, "reps": "12-15", "rest_seconds": 45}, {"name": "Brisk Walk / Incline Treadmill", "sets": 1, "reps": "20 min", "rest_seconds": 0}]}]'::jsonb),
  ('Fat Loss — Upper/Lower Burn', 'lose_fat', 'intermediate', '[{"day": "Mon", "focus": "Lower Body", "items": [{"name": "Barbell Back Squat", "sets": 4, "reps": "10-12", "rest_seconds": 60}, {"name": "Romanian Deadlift", "sets": 3, "reps": "10-12", "rest_seconds": 60}, {"name": "Walking Lunge", "sets": 3, "reps": "12/leg", "rest_seconds": 45}, {"name": "Leg Press", "sets": 3, "reps": "15", "rest_seconds": 45}, {"name": "Standing Calf Raise", "sets": 3, "reps": "15-20", "rest_seconds": 30}]}, {"day": "Tue", "focus": "Upper Body", "items": [{"name": "Incline Dumbbell Press", "sets": 4, "reps": "10-12", "rest_seconds": 60}, {"name": "Seated Cable Row", "sets": 4, "reps": "10-12", "rest_seconds": 60}, {"name": "Lateral Raise", "sets": 3, "reps": "15", "rest_seconds": 30}, {"name": "Face Pull", "sets": 3, "reps": "15", "rest_seconds": 30}, {"name": "Triceps Pushdown", "sets": 3, "reps": "12-15", "rest_seconds": 30}]}, {"day": "Thu", "focus": "Lower Body + Core", "items": [{"name": "Deadlift", "sets": 4, "reps": "8-10", "rest_seconds": 75}, {"name": "Bulgarian Split Squat", "sets": 3, "reps": "10/leg", "rest_seconds": 45}, {"name": "Hip Thrust", "sets": 3, "reps": "12-15", "rest_seconds": 45}, {"name": "Hanging Knee Raise", "sets": 3, "reps": "15", "rest_seconds": 30}]}, {"day": "Fri", "focus": "Upper Body + Conditioning", "items": [{"name": "Pull-Up (assisted if needed)", "sets": 4, "reps": "8-10", "rest_seconds": 60}, {"name": "Dumbbell Bench Press", "sets": 4, "reps": "10-12", "rest_seconds": 60}, {"name": "Arnold Press", "sets": 3, "reps": "10-12", "rest_seconds": 45}, {"name": "Circuit: Burpees / KB Swings / Rowing", "sets": 3, "reps": "40s work / 20s rest", "rest_seconds": 20}]}]'::jsonb),
  ('Fat Loss — 5-Day Shred', 'lose_fat', 'advanced', '[{"day": "Mon", "focus": "Legs", "items": [{"name": "Barbell Back Squat", "sets": 5, "reps": "8-10", "rest_seconds": 75}, {"name": "Romanian Deadlift", "sets": 4, "reps": "10", "rest_seconds": 60}, {"name": "Walking Lunge", "sets": 3, "reps": "15/leg", "rest_seconds": 45}, {"name": "Leg Extension", "sets": 3, "reps": "15", "rest_seconds": 30}, {"name": "Seated Calf Raise", "sets": 4, "reps": "15-20", "rest_seconds": 30}]}, {"day": "Tue", "focus": "Push", "items": [{"name": "Barbell Bench Press", "sets": 5, "reps": "8-10", "rest_seconds": 75}, {"name": "Overhead Press", "sets": 4, "reps": "8-10", "rest_seconds": 60}, {"name": "Incline Dumbbell Press", "sets": 3, "reps": "10-12", "rest_seconds": 45}, {"name": "Lateral Raise", "sets": 3, "reps": "15", "rest_seconds": 30}, {"name": "Triceps Dip", "sets": 3, "reps": "12-15", "rest_seconds": 30}]}, {"day": "Wed", "focus": "Conditioning", "items": [{"name": "Circuit: Row / Bike / Burpees / KB Swing", "sets": 5, "reps": "45s work / 15s rest", "rest_seconds": 15}]}, {"day": "Thu", "focus": "Pull", "items": [{"name": "Deadlift", "sets": 5, "reps": "6-8", "rest_seconds": 90}, {"name": "Pull-Up", "sets": 4, "reps": "8-10", "rest_seconds": 60}, {"name": "Barbell Row", "sets": 4, "reps": "10", "rest_seconds": 60}, {"name": "Face Pull", "sets": 3, "reps": "15", "rest_seconds": 30}, {"name": "Barbell Curl", "sets": 3, "reps": "12", "rest_seconds": 30}]}, {"day": "Fri", "focus": "Full Body + Cardio Finisher", "items": [{"name": "Front Squat", "sets": 4, "reps": "10", "rest_seconds": 60}, {"name": "Push Press", "sets": 3, "reps": "8-10", "rest_seconds": 60}, {"name": "Chin-Up", "sets": 3, "reps": "AMRAP", "rest_seconds": 45}, {"name": "Sled Push / Sprint Intervals", "sets": 6, "reps": "20s", "rest_seconds": 40}]}]'::jsonb),
  ('Muscle Building — Foundations', 'build_muscle', 'beginner', '[{"day": "Mon", "focus": "Full Body A", "items": [{"name": "Barbell Back Squat", "sets": 3, "reps": "8-10", "rest_seconds": 90}, {"name": "Dumbbell Bench Press", "sets": 3, "reps": "8-10", "rest_seconds": 90}, {"name": "Seated Row", "sets": 3, "reps": "10-12", "rest_seconds": 60}, {"name": "Dumbbell Shoulder Press", "sets": 3, "reps": "10-12", "rest_seconds": 60}, {"name": "Plank", "sets": 3, "reps": "45s", "rest_seconds": 30}]}, {"day": "Wed", "focus": "Full Body B", "items": [{"name": "Romanian Deadlift", "sets": 3, "reps": "8-10", "rest_seconds": 90}, {"name": "Incline Push-Up", "sets": 3, "reps": "8-10", "rest_seconds": 90}, {"name": "Lat Pulldown", "sets": 3, "reps": "10-12", "rest_seconds": 60}, {"name": "Leg Press", "sets": 3, "reps": "10-12", "rest_seconds": 60}, {"name": "Dumbbell Curl", "sets": 3, "reps": "12", "rest_seconds": 45}]}, {"day": "Fri", "focus": "Full Body C", "items": [{"name": "Goblet Squat", "sets": 3, "reps": "10-12", "rest_seconds": 60}, {"name": "Dumbbell Row", "sets": 3, "reps": "10-12", "rest_seconds": 60}, {"name": "Overhead Press", "sets": 3, "reps": "8-10", "rest_seconds": 90}, {"name": "Leg Curl", "sets": 3, "reps": "12", "rest_seconds": 45}, {"name": "Triceps Pushdown", "sets": 3, "reps": "12", "rest_seconds": 45}]}]'::jsonb),
  ('Muscle Building — Upper/Lower Hypertrophy', 'build_muscle', 'intermediate', '[{"day": "Mon", "focus": "Upper", "items": [{"name": "Barbell Bench Press", "sets": 4, "reps": "8-10", "rest_seconds": 90}, {"name": "Barbell Row", "sets": 4, "reps": "8-10", "rest_seconds": 90}, {"name": "Overhead Press", "sets": 3, "reps": "8-10", "rest_seconds": 75}, {"name": "Lat Pulldown", "sets": 3, "reps": "10-12", "rest_seconds": 60}, {"name": "Barbell Curl", "sets": 3, "reps": "10-12", "rest_seconds": 45}, {"name": "Triceps Pushdown", "sets": 3, "reps": "10-12", "rest_seconds": 45}]}, {"day": "Tue", "focus": "Lower", "items": [{"name": "Barbell Back Squat", "sets": 4, "reps": "8-10", "rest_seconds": 90}, {"name": "Romanian Deadlift", "sets": 4, "reps": "8-10", "rest_seconds": 90}, {"name": "Leg Press", "sets": 3, "reps": "10-12", "rest_seconds": 60}, {"name": "Leg Curl", "sets": 3, "reps": "10-12", "rest_seconds": 60}, {"name": "Standing Calf Raise", "sets": 4, "reps": "12-15", "rest_seconds": 45}]}, {"day": "Thu", "focus": "Upper", "items": [{"name": "Incline Dumbbell Press", "sets": 4, "reps": "8-10", "rest_seconds": 75}, {"name": "Pull-Up", "sets": 4, "reps": "8-10", "rest_seconds": 75}, {"name": "Dumbbell Shoulder Press", "sets": 3, "reps": "10-12", "rest_seconds": 60}, {"name": "Seated Cable Row", "sets": 3, "reps": "10-12", "rest_seconds": 60}, {"name": "Hammer Curl", "sets": 3, "reps": "10-12", "rest_seconds": 45}]}, {"day": "Fri", "focus": "Lower", "items": [{"name": "Front Squat", "sets": 4, "reps": "8-10", "rest_seconds": 90}, {"name": "Hip Thrust", "sets": 4, "reps": "10-12", "rest_seconds": 75}, {"name": "Walking Lunge", "sets": 3, "reps": "12/leg", "rest_seconds": 60}, {"name": "Leg Extension", "sets": 3, "reps": "12-15", "rest_seconds": 45}, {"name": "Seated Calf Raise", "sets": 4, "reps": "12-15", "rest_seconds": 45}]}]'::jsonb),
  ('Muscle Building — Push/Pull/Legs', 'build_muscle', 'advanced', '[{"day": "Mon", "focus": "Push", "items": [{"name": "Barbell Bench Press", "sets": 5, "reps": "6-8", "rest_seconds": 120}, {"name": "Overhead Press", "sets": 4, "reps": "8-10", "rest_seconds": 90}, {"name": "Incline Dumbbell Press", "sets": 4, "reps": "8-10", "rest_seconds": 75}, {"name": "Lateral Raise", "sets": 4, "reps": "12-15", "rest_seconds": 45}, {"name": "Triceps Dip", "sets": 4, "reps": "10-12", "rest_seconds": 60}]}, {"day": "Tue", "focus": "Pull", "items": [{"name": "Deadlift", "sets": 5, "reps": "5-6", "rest_seconds": 150}, {"name": "Pull-Up (weighted if possible)", "sets": 4, "reps": "6-8", "rest_seconds": 90}, {"name": "Barbell Row", "sets": 4, "reps": "8-10", "rest_seconds": 90}, {"name": "Face Pull", "sets": 3, "reps": "15", "rest_seconds": 45}, {"name": "Barbell Curl", "sets": 4, "reps": "10-12", "rest_seconds": 60}]}, {"day": "Wed", "focus": "Legs", "items": [{"name": "Barbell Back Squat", "sets": 5, "reps": "6-8", "rest_seconds": 120}, {"name": "Romanian Deadlift", "sets": 4, "reps": "8-10", "rest_seconds": 90}, {"name": "Bulgarian Split Squat", "sets": 3, "reps": "10/leg", "rest_seconds": 60}, {"name": "Leg Curl", "sets": 3, "reps": "12", "rest_seconds": 45}, {"name": "Standing Calf Raise", "sets": 4, "reps": "12-15", "rest_seconds": 45}]}, {"day": "Thu", "focus": "Push", "items": [{"name": "Overhead Press", "sets": 5, "reps": "6-8", "rest_seconds": 120}, {"name": "Dumbbell Bench Press", "sets": 4, "reps": "8-10", "rest_seconds": 90}, {"name": "Cable Fly", "sets": 3, "reps": "12-15", "rest_seconds": 45}, {"name": "Triceps Pushdown", "sets": 4, "reps": "10-12", "rest_seconds": 45}]}, {"day": "Fri", "focus": "Pull", "items": [{"name": "Barbell Row", "sets": 5, "reps": "6-8", "rest_seconds": 120}, {"name": "Lat Pulldown", "sets": 4, "reps": "8-10", "rest_seconds": 75}, {"name": "Seated Cable Row", "sets": 3, "reps": "10-12", "rest_seconds": 60}, {"name": "Hammer Curl", "sets": 3, "reps": "10-12", "rest_seconds": 45}]}, {"day": "Sat", "focus": "Legs", "items": [{"name": "Front Squat", "sets": 5, "reps": "6-8", "rest_seconds": 120}, {"name": "Walking Lunge", "sets": 4, "reps": "12/leg", "rest_seconds": 60}, {"name": "Leg Press", "sets": 4, "reps": "10-12", "rest_seconds": 75}, {"name": "Seated Calf Raise", "sets": 4, "reps": "12-15", "rest_seconds": 45}]}]'::jsonb),
  ('Maintenance — Balanced Full Body', 'maintain', 'beginner', '[{"day": "Mon", "focus": "Full Body A", "items": [{"name": "Bodyweight Squat", "sets": 3, "reps": "12-15", "rest_seconds": 60}, {"name": "Push-Up", "sets": 3, "reps": "10-12", "rest_seconds": 60}, {"name": "Dumbbell Row", "sets": 3, "reps": "10-12", "rest_seconds": 60}, {"name": "Plank", "sets": 3, "reps": "30-45s", "rest_seconds": 30}]}, {"day": "Wed", "focus": "Full Body B", "items": [{"name": "Goblet Squat", "sets": 3, "reps": "12", "rest_seconds": 60}, {"name": "Dumbbell Shoulder Press", "sets": 3, "reps": "10-12", "rest_seconds": 60}, {"name": "Lat Pulldown", "sets": 3, "reps": "10-12", "rest_seconds": 60}, {"name": "Glute Bridge", "sets": 3, "reps": "15", "rest_seconds": 45}]}, {"day": "Fri", "focus": "Full Body C + Light Cardio", "items": [{"name": "Walking Lunge", "sets": 3, "reps": "10/leg", "rest_seconds": 45}, {"name": "Seated Row", "sets": 3, "reps": "12", "rest_seconds": 60}, {"name": "Incline Push-Up", "sets": 3, "reps": "12", "rest_seconds": 45}, {"name": "Brisk Walk", "sets": 1, "reps": "20 min", "rest_seconds": 0}]}]'::jsonb),
  ('Maintenance — Balanced Split', 'maintain', 'intermediate', '[{"day": "Mon", "focus": "Upper", "items": [{"name": "Dumbbell Bench Press", "sets": 3, "reps": "10-12", "rest_seconds": 60}, {"name": "Seated Row", "sets": 3, "reps": "10-12", "rest_seconds": 60}, {"name": "Dumbbell Shoulder Press", "sets": 3, "reps": "10-12", "rest_seconds": 60}, {"name": "Triceps Pushdown", "sets": 3, "reps": "12", "rest_seconds": 45}]}, {"day": "Tue", "focus": "Lower", "items": [{"name": "Barbell Back Squat", "sets": 3, "reps": "10-12", "rest_seconds": 75}, {"name": "Romanian Deadlift", "sets": 3, "reps": "10-12", "rest_seconds": 75}, {"name": "Leg Press", "sets": 3, "reps": "12", "rest_seconds": 60}, {"name": "Standing Calf Raise", "sets": 3, "reps": "15", "rest_seconds": 45}]}, {"day": "Thu", "focus": "Upper", "items": [{"name": "Pull-Up (assisted if needed)", "sets": 3, "reps": "8-10", "rest_seconds": 75}, {"name": "Incline Dumbbell Press", "sets": 3, "reps": "10-12", "rest_seconds": 60}, {"name": "Face Pull", "sets": 3, "reps": "15", "rest_seconds": 45}, {"name": "Barbell Curl", "sets": 3, "reps": "12", "rest_seconds": 45}]}, {"day": "Fri", "focus": "Lower + Core", "items": [{"name": "Walking Lunge", "sets": 3, "reps": "12/leg", "rest_seconds": 60}, {"name": "Hip Thrust", "sets": 3, "reps": "12-15", "rest_seconds": 60}, {"name": "Leg Curl", "sets": 3, "reps": "12", "rest_seconds": 45}, {"name": "Hanging Knee Raise", "sets": 3, "reps": "15", "rest_seconds": 30}]}]'::jsonb),
  ('Maintenance — Athletic Upkeep', 'maintain', 'advanced', '[{"day": "Mon", "focus": "Push", "items": [{"name": "Barbell Bench Press", "sets": 4, "reps": "8-10", "rest_seconds": 90}, {"name": "Overhead Press", "sets": 3, "reps": "8-10", "rest_seconds": 75}, {"name": "Lateral Raise", "sets": 3, "reps": "12-15", "rest_seconds": 45}, {"name": "Triceps Dip", "sets": 3, "reps": "10-12", "rest_seconds": 45}]}, {"day": "Tue", "focus": "Pull", "items": [{"name": "Deadlift", "sets": 4, "reps": "6-8", "rest_seconds": 120}, {"name": "Pull-Up", "sets": 3, "reps": "8-10", "rest_seconds": 75}, {"name": "Barbell Row", "sets": 3, "reps": "10", "rest_seconds": 75}, {"name": "Barbell Curl", "sets": 3, "reps": "10-12", "rest_seconds": 45}]}, {"day": "Wed", "focus": "Conditioning", "items": [{"name": "Circuit: Row / Bike / Bodyweight Combo", "sets": 4, "reps": "40s work / 20s rest", "rest_seconds": 20}]}, {"day": "Thu", "focus": "Legs", "items": [{"name": "Barbell Back Squat", "sets": 4, "reps": "8-10", "rest_seconds": 90}, {"name": "Bulgarian Split Squat", "sets": 3, "reps": "10/leg", "rest_seconds": 60}, {"name": "Leg Curl", "sets": 3, "reps": "12", "rest_seconds": 45}, {"name": "Standing Calf Raise", "sets": 3, "reps": "15", "rest_seconds": 45}]}, {"day": "Fri", "focus": "Full Body", "items": [{"name": "Front Squat", "sets": 3, "reps": "10", "rest_seconds": 75}, {"name": "Incline Dumbbell Press", "sets": 3, "reps": "10", "rest_seconds": 60}, {"name": "Seated Cable Row", "sets": 3, "reps": "10-12", "rest_seconds": 60}, {"name": "Plank", "sets": 3, "reps": "45-60s", "rest_seconds": 30}]}]'::jsonb);

insert into public.exercises (name, muscle_group, equipment, difficulty) values
  ('Barbell Back Squat', 'Legs', 'Barbell', 'intermediate'),
  ('Front Squat', 'Legs', 'Barbell', 'advanced'),
  ('Bodyweight Squat', 'Legs', 'None', 'beginner'),
  ('Goblet Squat', 'Legs', 'Dumbbell', 'beginner'),
  ('Romanian Deadlift', 'Hamstrings', 'Barbell', 'intermediate'),
  ('Deadlift', 'Back', 'Barbell', 'advanced'),
  ('Walking Lunge', 'Legs', 'Dumbbell', 'beginner'),
  ('Bulgarian Split Squat', 'Legs', 'Dumbbell', 'intermediate'),
  ('Leg Press', 'Legs', 'Machine', 'beginner'),
  ('Leg Curl', 'Hamstrings', 'Machine', 'beginner'),
  ('Leg Extension', 'Quads', 'Machine', 'beginner'),
  ('Hip Thrust', 'Glutes', 'Barbell', 'intermediate'),
  ('Standing Calf Raise', 'Calves', 'Machine', 'beginner'),
  ('Seated Calf Raise', 'Calves', 'Machine', 'beginner'),
  ('Step-Up', 'Legs', 'Dumbbell', 'beginner'),
  ('Barbell Bench Press', 'Chest', 'Barbell', 'intermediate'),
  ('Dumbbell Bench Press', 'Chest', 'Dumbbell', 'beginner'),
  ('Incline Dumbbell Press', 'Chest', 'Dumbbell', 'intermediate'),
  ('Push-Up', 'Chest', 'None', 'beginner'),
  ('Incline Push-Up', 'Chest', 'None', 'beginner'),
  ('Cable Fly', 'Chest', 'Cable', 'intermediate'),
  ('Overhead Press', 'Shoulders', 'Barbell', 'intermediate'),
  ('Dumbbell Shoulder Press', 'Shoulders', 'Dumbbell', 'beginner'),
  ('Arnold Press', 'Shoulders', 'Dumbbell', 'intermediate'),
  ('Lateral Raise', 'Shoulders', 'Dumbbell', 'beginner'),
  ('Push Press', 'Shoulders', 'Barbell', 'advanced'),
  ('Barbell Row', 'Back', 'Barbell', 'intermediate'),
  ('Dumbbell Row', 'Back', 'Dumbbell', 'beginner'),
  ('Seated Row', 'Back', 'Machine', 'beginner'),
  ('Seated Cable Row', 'Back', 'Cable', 'beginner'),
  ('Lat Pulldown', 'Back', 'Cable', 'beginner'),
  ('Pull-Up', 'Back', 'None', 'intermediate'),
  ('Chin-Up', 'Back', 'None', 'intermediate'),
  ('Face Pull', 'Shoulders', 'Cable', 'beginner'),
  ('Barbell Curl', 'Biceps', 'Barbell', 'beginner'),
  ('Dumbbell Curl', 'Biceps', 'Dumbbell', 'beginner'),
  ('Hammer Curl', 'Biceps', 'Dumbbell', 'beginner'),
  ('Triceps Pushdown', 'Triceps', 'Cable', 'beginner'),
  ('Triceps Dip', 'Triceps', 'None', 'intermediate'),
  ('Plank', 'Core', 'None', 'beginner'),
  ('Hanging Knee Raise', 'Core', 'None', 'intermediate'),
  ('Mountain Climbers', 'Core', 'None', 'beginner'),
  ('Glute Bridge', 'Glutes', 'None', 'beginner'),
  ('Jump Squat', 'Legs', 'None', 'intermediate'),
  ('Dumbbell Romanian Deadlift', 'Hamstrings', 'Dumbbell', 'beginner'),
  ('Dumbbell Deadlift', 'Back', 'Dumbbell', 'beginner'),
  ('Single-Leg Glute Bridge', 'Glutes', 'None', 'beginner'),
  ('Glute Bridge March', 'Hamstrings', 'None', 'beginner'),
  ('Wall Sit', 'Quads', 'None', 'beginner'),
  ('Dumbbell Hip Thrust', 'Glutes', 'Dumbbell', 'beginner'),
  ('Calf Raise', 'Calves', 'None', 'beginner'),
  ('Single-Leg Calf Raise', 'Calves', 'None', 'intermediate'),
  ('Decline Push-Up', 'Chest', 'None', 'intermediate'),
  ('Wide Push-Up', 'Chest', 'None', 'beginner'),
  ('Pike Push-Up', 'Shoulders', 'None', 'intermediate'),
  ('Dumbbell Push Press', 'Shoulders', 'Dumbbell', 'intermediate'),
  ('Superman Row', 'Back', 'None', 'beginner'),
  ('Rear Delt Fly', 'Shoulders', 'Dumbbell', 'beginner'),
  ('Lying Leg Raise', 'Core', 'None', 'beginner'),
  ('Band Deadlift', 'Back', 'Resistance Band', 'beginner'),
  ('Band Leg Curl', 'Hamstrings', 'Resistance Band', 'beginner'),
  ('Band Leg Extension', 'Quads', 'Resistance Band', 'beginner'),
  ('Band Chest Fly', 'Chest', 'Resistance Band', 'beginner'),
  ('Band Lateral Raise', 'Shoulders', 'Resistance Band', 'beginner'),
  ('Band Row', 'Back', 'Resistance Band', 'beginner'),
  ('Band Pulldown', 'Back', 'Resistance Band', 'beginner'),
  ('Band Face Pull', 'Shoulders', 'Resistance Band', 'beginner'),
  ('Band Curl', 'Biceps', 'Resistance Band', 'beginner'),
  ('Band Triceps Extension', 'Triceps', 'Resistance Band', 'beginner'),
  ('Plank Shoulder Tap', 'Shoulders', 'None', 'beginner'),
  ('Prone Y-Raise', 'Shoulders', 'None', 'beginner'),
  ('Towel Curl', 'Biceps', 'None', 'beginner');
