/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CmsRouteImport } from './routes/cms'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CmsIndexRouteImport } from './routes/cms.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CmsTagsRouteImport } from './routes/cms.tags'
import { Route as CmsMediaRouteImport } from './routes/cms.media'
import { Route as CmsCategoriesRouteImport } from './routes/cms.categories'
import { Route as CmsArticlesRouteImport } from './routes/cms.articles'
import { Route as BlogSearchRouteImport } from './routes/blog.search'
import { Route as BlogRssDotxmlRouteImport } from './routes/blog.rss[.]xml'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminWorkoutsRouteImport } from './routes/admin.workouts'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminFoodsRouteImport } from './routes/admin.foods'
import { Route as AdminExercisesRouteImport } from './routes/admin.exercises'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AppWorkoutsRouteImport } from './routes/_app.workouts'
import { Route as AppWorkoutHistoryRouteImport } from './routes/_app.workout-history'
import { Route as AppSupportRouteImport } from './routes/_app.support'
import { Route as AppSubscriptionRouteImport } from './routes/_app.subscription'
import { Route as AppProgressRouteImport } from './routes/_app.progress'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppOnboardingRouteImport } from './routes/_app.onboarding'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppMealsRouteImport } from './routes/_app.meals'
import { Route as AppFoodDiaryRouteImport } from './routes/_app.food-diary'
import { Route as AppFeedbackRouteImport } from './routes/_app.feedback'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as CmsArticlesNewRouteImport } from './routes/cms.articles.new'
import { Route as CmsArticlesIdRouteImport } from './routes/cms.articles.$id'
import { Route as BlogTagSlugRouteImport } from './routes/blog.tag.$slug'
import { Route as BlogCategorySlugRouteImport } from './routes/blog.category.$slug'
import { Route as BlogAuthorSlugRouteImport } from './routes/blog.author.$slug'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicLemonsqueezyWebhookRouteImport } from './routes/api/public/lemonsqueezy/webhook'
import { Route as ApiPublicGooglePlayRtdnRouteImport } from './routes/api/public/google-play/rtdn'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsRoute = CmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsIndexRoute = CmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CmsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsTagsRoute = CmsTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => CmsRoute,
} as any)
const CmsMediaRoute = CmsMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => CmsRoute,
} as any)
const CmsCategoriesRoute = CmsCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => CmsRoute,
} as any)
const CmsArticlesRoute = CmsArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => CmsRoute,
} as any)
const BlogSearchRoute = BlogSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => BlogRoute,
} as any)
const BlogRssDotxmlRoute = BlogRssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminWorkoutsRoute = AdminWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFoodsRoute = AdminFoodsRouteImport.update({
  id: '/foods',
  path: '/foods',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExercisesRoute = AdminExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AppWorkoutsRoute = AppWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkoutHistoryRoute = AppWorkoutHistoryRouteImport.update({
  id: '/workout-history',
  path: '/workout-history',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMealsRoute = AppMealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => AppRoute,
} as any)
const AppFoodDiaryRoute = AppFoodDiaryRouteImport.update({
  id: '/food-diary',
  path: '/food-diary',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsArticlesNewRoute = CmsArticlesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CmsArticlesRoute,
} as any)
const CmsArticlesIdRoute = CmsArticlesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CmsArticlesRoute,
} as any)
const BlogTagSlugRoute = BlogTagSlugRouteImport.update({
  id: '/tag/$slug',
  path: '/tag/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const BlogCategorySlugRoute = BlogCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const BlogAuthorSlugRoute = BlogAuthorSlugRouteImport.update({
  id: '/author/$slug',
  path: '/author/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLemonsqueezyWebhookRoute =
  ApiPublicLemonsqueezyWebhookRouteImport.update({
    id: '/api/public/lemonsqueezy/webhook',
    path: '/api/public/lemonsqueezy/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGooglePlayRtdnRoute = ApiPublicGooglePlayRtdnRouteImport.update({
  id: '/api/public/google-play/rtdn',
  path: '/api/public/google-play/rtdn',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/cms': typeof CmsRouteWithChildren
  '/contact': typeof ContactRoute
  '/delete-account': typeof DeleteAccountRoute
  '/download': typeof DownloadRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/feedback': typeof AppFeedbackRoute
  '/food-diary': typeof AppFoodDiaryRoute
  '/meals': typeof AppMealsRoute
  '/notifications': typeof AppNotificationsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/profile': typeof AppProfileRoute
  '/progress': typeof AppProgressRoute
  '/subscription': typeof AppSubscriptionRoute
  '/support': typeof AppSupportRoute
  '/workout-history': typeof AppWorkoutHistoryRoute
  '/workouts': typeof AppWorkoutsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/exercises': typeof AdminExercisesRoute
  '/admin/foods': typeof AdminFoodsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workouts': typeof AdminWorkoutsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/blog/search': typeof BlogSearchRoute
  '/cms/articles': typeof CmsArticlesRouteWithChildren
  '/cms/categories': typeof CmsCategoriesRoute
  '/cms/media': typeof CmsMediaRoute
  '/cms/tags': typeof CmsTagsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/': typeof AdminIndexRoute
  '/cms/': typeof CmsIndexRoute
  '/blog/author/$slug': typeof BlogAuthorSlugRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/blog/tag/$slug': typeof BlogTagSlugRoute
  '/cms/articles/$id': typeof CmsArticlesIdRoute
  '/cms/articles/new': typeof CmsArticlesNewRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/google-play/rtdn': typeof ApiPublicGooglePlayRtdnRoute
  '/api/public/lemonsqueezy/webhook': typeof ApiPublicLemonsqueezyWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/delete-account': typeof DeleteAccountRoute
  '/download': typeof DownloadRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/feedback': typeof AppFeedbackRoute
  '/food-diary': typeof AppFoodDiaryRoute
  '/meals': typeof AppMealsRoute
  '/notifications': typeof AppNotificationsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/profile': typeof AppProfileRoute
  '/progress': typeof AppProgressRoute
  '/subscription': typeof AppSubscriptionRoute
  '/support': typeof AppSupportRoute
  '/workout-history': typeof AppWorkoutHistoryRoute
  '/workouts': typeof AppWorkoutsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/exercises': typeof AdminExercisesRoute
  '/admin/foods': typeof AdminFoodsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workouts': typeof AdminWorkoutsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/blog/search': typeof BlogSearchRoute
  '/cms/articles': typeof CmsArticlesRouteWithChildren
  '/cms/categories': typeof CmsCategoriesRoute
  '/cms/media': typeof CmsMediaRoute
  '/cms/tags': typeof CmsTagsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin': typeof AdminIndexRoute
  '/cms': typeof CmsIndexRoute
  '/blog/author/$slug': typeof BlogAuthorSlugRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/blog/tag/$slug': typeof BlogTagSlugRoute
  '/cms/articles/$id': typeof CmsArticlesIdRoute
  '/cms/articles/new': typeof CmsArticlesNewRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/google-play/rtdn': typeof ApiPublicGooglePlayRtdnRoute
  '/api/public/lemonsqueezy/webhook': typeof ApiPublicLemonsqueezyWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/cms': typeof CmsRouteWithChildren
  '/contact': typeof ContactRoute
  '/delete-account': typeof DeleteAccountRoute
  '/download': typeof DownloadRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/feedback': typeof AppFeedbackRoute
  '/_app/food-diary': typeof AppFoodDiaryRoute
  '/_app/meals': typeof AppMealsRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/progress': typeof AppProgressRoute
  '/_app/subscription': typeof AppSubscriptionRoute
  '/_app/support': typeof AppSupportRoute
  '/_app/workout-history': typeof AppWorkoutHistoryRoute
  '/_app/workouts': typeof AppWorkoutsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/exercises': typeof AdminExercisesRoute
  '/admin/foods': typeof AdminFoodsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workouts': typeof AdminWorkoutsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/blog/search': typeof BlogSearchRoute
  '/cms/articles': typeof CmsArticlesRouteWithChildren
  '/cms/categories': typeof CmsCategoriesRoute
  '/cms/media': typeof CmsMediaRoute
  '/cms/tags': typeof CmsTagsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/': typeof AdminIndexRoute
  '/cms/': typeof CmsIndexRoute
  '/blog/author/$slug': typeof BlogAuthorSlugRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/blog/tag/$slug': typeof BlogTagSlugRoute
  '/cms/articles/$id': typeof CmsArticlesIdRoute
  '/cms/articles/new': typeof CmsArticlesNewRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/google-play/rtdn': typeof ApiPublicGooglePlayRtdnRoute
  '/api/public/lemonsqueezy/webhook': typeof ApiPublicLemonsqueezyWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/cms'
    | '/contact'
    | '/delete-account'
    | '/download'
    | '/faq'
    | '/features'
    | '/forgot-password'
    | '/pricing'
    | '/privacy'
    | '/refunds'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/billing'
    | '/dashboard'
    | '/feedback'
    | '/food-diary'
    | '/meals'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/progress'
    | '/subscription'
    | '/support'
    | '/workout-history'
    | '/workouts'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/exercises'
    | '/admin/foods'
    | '/admin/media'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/admin/workouts'
    | '/blog/$slug'
    | '/blog/rss.xml'
    | '/blog/search'
    | '/cms/articles'
    | '/cms/categories'
    | '/cms/media'
    | '/cms/tags'
    | '/email/unsubscribe'
    | '/admin/'
    | '/cms/'
    | '/blog/author/$slug'
    | '/blog/category/$slug'
    | '/blog/tag/$slug'
    | '/cms/articles/$id'
    | '/cms/articles/new'
    | '/lovable/email/suppression'
    | '/api/public/google-play/rtdn'
    | '/api/public/lemonsqueezy/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/delete-account'
    | '/download'
    | '/faq'
    | '/features'
    | '/forgot-password'
    | '/pricing'
    | '/privacy'
    | '/refunds'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/billing'
    | '/dashboard'
    | '/feedback'
    | '/food-diary'
    | '/meals'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/progress'
    | '/subscription'
    | '/support'
    | '/workout-history'
    | '/workouts'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/exercises'
    | '/admin/foods'
    | '/admin/media'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/admin/workouts'
    | '/blog/$slug'
    | '/blog/rss.xml'
    | '/blog/search'
    | '/cms/articles'
    | '/cms/categories'
    | '/cms/media'
    | '/cms/tags'
    | '/email/unsubscribe'
    | '/admin'
    | '/cms'
    | '/blog/author/$slug'
    | '/blog/category/$slug'
    | '/blog/tag/$slug'
    | '/cms/articles/$id'
    | '/cms/articles/new'
    | '/lovable/email/suppression'
    | '/api/public/google-play/rtdn'
    | '/api/public/lemonsqueezy/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/cms'
    | '/contact'
    | '/delete-account'
    | '/download'
    | '/faq'
    | '/features'
    | '/forgot-password'
    | '/pricing'
    | '/privacy'
    | '/refunds'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/_app/billing'
    | '/_app/dashboard'
    | '/_app/feedback'
    | '/_app/food-diary'
    | '/_app/meals'
    | '/_app/notifications'
    | '/_app/onboarding'
    | '/_app/profile'
    | '/_app/progress'
    | '/_app/subscription'
    | '/_app/support'
    | '/_app/workout-history'
    | '/_app/workouts'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/exercises'
    | '/admin/foods'
    | '/admin/media'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/admin/workouts'
    | '/blog/$slug'
    | '/blog/rss.xml'
    | '/blog/search'
    | '/cms/articles'
    | '/cms/categories'
    | '/cms/media'
    | '/cms/tags'
    | '/email/unsubscribe'
    | '/admin/'
    | '/cms/'
    | '/blog/author/$slug'
    | '/blog/category/$slug'
    | '/blog/tag/$slug'
    | '/cms/articles/$id'
    | '/cms/articles/new'
    | '/lovable/email/suppression'
    | '/api/public/google-play/rtdn'
    | '/api/public/lemonsqueezy/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  CmsRoute: typeof CmsRouteWithChildren
  ContactRoute: typeof ContactRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  DownloadRoute: typeof DownloadRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundsRoute: typeof RefundsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicGooglePlayRtdnRoute: typeof ApiPublicGooglePlayRtdnRoute
  ApiPublicLemonsqueezyWebhookRoute: typeof ApiPublicLemonsqueezyWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms': {
      id: '/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof CmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms/': {
      id: '/cms/'
      path: '/'
      fullPath: '/cms/'
      preLoaderRoute: typeof CmsIndexRouteImport
      parentRoute: typeof CmsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms/tags': {
      id: '/cms/tags'
      path: '/tags'
      fullPath: '/cms/tags'
      preLoaderRoute: typeof CmsTagsRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/media': {
      id: '/cms/media'
      path: '/media'
      fullPath: '/cms/media'
      preLoaderRoute: typeof CmsMediaRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/categories': {
      id: '/cms/categories'
      path: '/categories'
      fullPath: '/cms/categories'
      preLoaderRoute: typeof CmsCategoriesRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/articles': {
      id: '/cms/articles'
      path: '/articles'
      fullPath: '/cms/articles'
      preLoaderRoute: typeof CmsArticlesRouteImport
      parentRoute: typeof CmsRoute
    }
    '/blog/search': {
      id: '/blog/search'
      path: '/search'
      fullPath: '/blog/search'
      preLoaderRoute: typeof BlogSearchRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/rss.xml': {
      id: '/blog/rss.xml'
      path: '/rss.xml'
      fullPath: '/blog/rss.xml'
      preLoaderRoute: typeof BlogRssDotxmlRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/workouts': {
      id: '/admin/workouts'
      path: '/workouts'
      fullPath: '/admin/workouts'
      preLoaderRoute: typeof AdminWorkoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/foods': {
      id: '/admin/foods'
      path: '/foods'
      fullPath: '/admin/foods'
      preLoaderRoute: typeof AdminFoodsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exercises': {
      id: '/admin/exercises'
      path: '/exercises'
      fullPath: '/admin/exercises'
      preLoaderRoute: typeof AdminExercisesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/workouts': {
      id: '/_app/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof AppWorkoutsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workout-history': {
      id: '/_app/workout-history'
      path: '/workout-history'
      fullPath: '/workout-history'
      preLoaderRoute: typeof AppWorkoutHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subscription': {
      id: '/_app/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progress': {
      id: '/_app/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meals': {
      id: '/_app/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof AppMealsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/food-diary': {
      id: '/_app/food-diary'
      path: '/food-diary'
      fullPath: '/food-diary'
      preLoaderRoute: typeof AppFoodDiaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feedback': {
      id: '/_app/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms/articles/new': {
      id: '/cms/articles/new'
      path: '/new'
      fullPath: '/cms/articles/new'
      preLoaderRoute: typeof CmsArticlesNewRouteImport
      parentRoute: typeof CmsArticlesRoute
    }
    '/cms/articles/$id': {
      id: '/cms/articles/$id'
      path: '/$id'
      fullPath: '/cms/articles/$id'
      preLoaderRoute: typeof CmsArticlesIdRouteImport
      parentRoute: typeof CmsArticlesRoute
    }
    '/blog/tag/$slug': {
      id: '/blog/tag/$slug'
      path: '/tag/$slug'
      fullPath: '/blog/tag/$slug'
      preLoaderRoute: typeof BlogTagSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/category/$slug': {
      id: '/blog/category/$slug'
      path: '/category/$slug'
      fullPath: '/blog/category/$slug'
      preLoaderRoute: typeof BlogCategorySlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/author/$slug': {
      id: '/blog/author/$slug'
      path: '/author/$slug'
      fullPath: '/blog/author/$slug'
      preLoaderRoute: typeof BlogAuthorSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lemonsqueezy/webhook': {
      id: '/api/public/lemonsqueezy/webhook'
      path: '/api/public/lemonsqueezy/webhook'
      fullPath: '/api/public/lemonsqueezy/webhook'
      preLoaderRoute: typeof ApiPublicLemonsqueezyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google-play/rtdn': {
      id: '/api/public/google-play/rtdn'
      path: '/api/public/google-play/rtdn'
      fullPath: '/api/public/google-play/rtdn'
      preLoaderRoute: typeof ApiPublicGooglePlayRtdnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppFoodDiaryRoute: typeof AppFoodDiaryRoute
  AppMealsRoute: typeof AppMealsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProgressRoute: typeof AppProgressRoute
  AppSubscriptionRoute: typeof AppSubscriptionRoute
  AppSupportRoute: typeof AppSupportRoute
  AppWorkoutHistoryRoute: typeof AppWorkoutHistoryRoute
  AppWorkoutsRoute: typeof AppWorkoutsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFeedbackRoute: AppFeedbackRoute,
  AppFoodDiaryRoute: AppFoodDiaryRoute,
  AppMealsRoute: AppMealsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppProfileRoute: AppProfileRoute,
  AppProgressRoute: AppProgressRoute,
  AppSubscriptionRoute: AppSubscriptionRoute,
  AppSupportRoute: AppSupportRoute,
  AppWorkoutHistoryRoute: AppWorkoutHistoryRoute,
  AppWorkoutsRoute: AppWorkoutsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminExercisesRoute: typeof AdminExercisesRoute
  AdminFoodsRoute: typeof AdminFoodsRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWorkoutsRoute: typeof AdminWorkoutsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminExercisesRoute: AdminExercisesRoute,
  AdminFoodsRoute: AdminFoodsRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWorkoutsRoute: AdminWorkoutsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogRssDotxmlRoute: typeof BlogRssDotxmlRoute
  BlogSearchRoute: typeof BlogSearchRoute
  BlogAuthorSlugRoute: typeof BlogAuthorSlugRoute
  BlogCategorySlugRoute: typeof BlogCategorySlugRoute
  BlogTagSlugRoute: typeof BlogTagSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogRssDotxmlRoute: BlogRssDotxmlRoute,
  BlogSearchRoute: BlogSearchRoute,
  BlogAuthorSlugRoute: BlogAuthorSlugRoute,
  BlogCategorySlugRoute: BlogCategorySlugRoute,
  BlogTagSlugRoute: BlogTagSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CmsArticlesRouteChildren {
  CmsArticlesIdRoute: typeof CmsArticlesIdRoute
  CmsArticlesNewRoute: typeof CmsArticlesNewRoute
}

const CmsArticlesRouteChildren: CmsArticlesRouteChildren = {
  CmsArticlesIdRoute: CmsArticlesIdRoute,
  CmsArticlesNewRoute: CmsArticlesNewRoute,
}

const CmsArticlesRouteWithChildren = CmsArticlesRoute._addFileChildren(
  CmsArticlesRouteChildren,
)

interface CmsRouteChildren {
  CmsArticlesRoute: typeof CmsArticlesRouteWithChildren
  CmsCategoriesRoute: typeof CmsCategoriesRoute
  CmsMediaRoute: typeof CmsMediaRoute
  CmsTagsRoute: typeof CmsTagsRoute
  CmsIndexRoute: typeof CmsIndexRoute
}

const CmsRouteChildren: CmsRouteChildren = {
  CmsArticlesRoute: CmsArticlesRouteWithChildren,
  CmsCategoriesRoute: CmsCategoriesRoute,
  CmsMediaRoute: CmsMediaRoute,
  CmsTagsRoute: CmsTagsRoute,
  CmsIndexRoute: CmsIndexRoute,
}

const CmsRouteWithChildren = CmsRoute._addFileChildren(CmsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  CmsRoute: CmsRouteWithChildren,
  ContactRoute: ContactRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  DownloadRoute: DownloadRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundsRoute: RefundsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicGooglePlayRtdnRoute: ApiPublicGooglePlayRtdnRoute,
  ApiPublicLemonsqueezyWebhookRoute: ApiPublicLemonsqueezyWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
