// Google Play Real-Time Developer Notifications (RTDN) push endpoint.
//
// Without this, the app only learns a subscription's true state at the
// moment of purchase or when the user manually taps "Restore purchases" —
// an auto-renewal, a cancellation, a billing failure entering grace period,
// or Google revoking a purchase would never reach us, and a still-paying
// Pro subscriber would eventually get silently downgraded to free the
// moment their ORIGINAL purchase's expiry timestamp passed, even though
// Google kept renewing them. RTDN closes that gap: Google Cloud Pub/Sub
// pushes a message here on every subscription lifecycle event, and we
// re-verify the referenced purchase token against the real Play Developer
// API (the same call every other verification path uses) and write
// whatever is CURRENTLY true — never trusting the notification payload
// itself for anything except "go re-check this token".
//
// Setup (Play Console + Google Cloud Console — see PLAY_STORE_RELEASE.md):
//   1. Create a Pub/Sub topic in the same GCP project as the Play Console
//      app, and grant publish rights to google-play-developer-notifications@system.gserviceaccount.com.
//   2. Play Console -> Monetization setup -> Real-time developer
//      notifications -> set that topic.
//   3. Create a PUSH subscription on the topic pointing at:
//        https://<your-domain>/api/public/google-play/rtdn?token=<GOOGLE_PLAY_RTDN_SECRET>
//      using the exact same secret value as the GOOGLE_PLAY_RTDN_SECRET
//      server env var (generate any long random string for it — this is a
//      webhook secret you create yourself, not a Google credential).
import { createFileRoute } from "@tanstack/react-router";
import { processPlayRtdnNotification } from "@/lib/billing.functions";

const PACKAGE_NAME = "com.fitplancoach.app";

const NOTIFICATION_TYPE_NAMES: Record<number, string> = {
  1: "SUBSCRIPTION_RECOVERED",
  2: "SUBSCRIPTION_RENEWED",
  3: "SUBSCRIPTION_CANCELED",
  4: "SUBSCRIPTION_PURCHASED",
  5: "SUBSCRIPTION_ON_HOLD",
  6: "SUBSCRIPTION_IN_GRACE_PERIOD",
  7: "SUBSCRIPTION_RESTARTED",
  8: "SUBSCRIPTION_PRICE_CHANGE_CONFIRMED",
  9: "SUBSCRIPTION_DEFERRED",
  10: "SUBSCRIPTION_PAUSED",
  11: "SUBSCRIPTION_PAUSE_SCHEDULE_CHANGED",
  12: "SUBSCRIPTION_REVOKED",
  13: "SUBSCRIPTION_EXPIRED",
};

const ok = () => new Response("ok", { status: 200 });

export const Route = createFileRoute("/api/public/google-play/rtdn")({
  server: {
    handlers: {
      // Lets you sanity-check the URL resolves in a browser; Pub/Sub itself only ever POSTs.
      GET: async () => ok(),

      POST: async ({ request }) => {
        // Pub/Sub push authentication: a shared-secret query token, per
        // Google's own documented pattern for securing push endpoints
        // (https://cloud.google.com/pubsub/docs/push#authentication). The
        // secret is never sent to or generated by us — the operator creates
        // it and puts the same value in both the env var and the push
        // subscription URL.
        const expected = process.env.GOOGLE_PLAY_RTDN_SECRET;
        const url = new URL(request.url);
        const token = url.searchParams.get("token");
        if (!expected) {
          console.error("[rtdn] GOOGLE_PLAY_RTDN_SECRET not configured — rejecting all pushes");
          return new Response("Unauthorized", { status: 401 });
        }
        if (token !== expected) {
          console.warn("[rtdn] rejected push with invalid/missing token");
          return new Response("Unauthorized", { status: 401 });
        }

        let body: { message?: { messageId?: string; data?: string } };
        try {
          body = await request.json();
        } catch {
          // Not something a retry will fix — ack so Pub/Sub stops resending it.
          return ok();
        }

        const messageId = body.message?.messageId;
        const dataB64 = body.message?.data;
        if (!messageId || !dataB64) return ok();

        let notification: {
          packageName?: string;
          testNotification?: unknown;
          subscriptionNotification?: { notificationType?: number; purchaseToken?: string };
        };
        try {
          notification = JSON.parse(Buffer.from(dataB64, "base64").toString("utf8"));
        } catch {
          return ok();
        }

        const { supabaseAdmin } = await import("@/integrations/supabase/client.server");

        // Idempotency: Pub/Sub guarantees at-least-once delivery, so the same
        // message can arrive more than once. webhook_events' UNIQUE(provider,
        // event_id) makes the second insert fail, and we treat that as
        // "already handled" rather than reprocessing.
        const sub = notification.subscriptionNotification;
        const eventName = notification.testNotification
          ? "TEST_NOTIFICATION"
          : sub?.notificationType != null
            ? (NOTIFICATION_TYPE_NAMES[sub.notificationType] ?? `UNKNOWN_${sub.notificationType}`)
            : "UNKNOWN";

        const { error: insertError } = await supabaseAdmin.from("webhook_events").insert({
          provider: "google_play_rtdn",
          event_id: messageId,
          event_name: eventName,
          payload: notification as never,
        });
        if (insertError) {
          if (insertError.code === "23505" /* unique_violation */) {
            return ok(); // already processed this exact Pub/Sub message
          }
          // Audit-logging failure shouldn't block entitlement sync — log and continue.
          console.error("[rtdn] failed to record webhook event", insertError);
        }

        if (notification.testNotification) return ok(); // Play Console's "Send test notification" button
        if (notification.packageName && notification.packageName !== PACKAGE_NAME) return ok();
        if (!sub?.purchaseToken) return ok(); // one-time-product notifications etc. — not applicable, we only sell subscriptions

        await processPlayRtdnNotification(sub.purchaseToken);
        return ok();
      },
    },
  },
});
